---
- name: create journald.conf.d
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: template journald.conf override
  ansible.builtin.template:
    src: 99-retention.conf
    dest: /etc/systemd/journald.conf.d/
  register: retention

- name: restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
  when: retention.changed

- name: copy 99-history-files.sh
  ansible.builtin.copy:
    src: 99-history-files.sh
    dest: /etc/profile.d/
  when: basics_history_disabled

- name: delete 99-history-files.sh
  ansible.builtin.file:
    path: /etc/profile.d/99-history-files.sh
    state: absent
  when: not basics_history_disabled

- name: delete history files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/.bash_history
    - /root/.lesshst
  when: basics_history_disabled
