---
- ansible.builtin.include_tasks: pre-tasks.yml
- ansible.builtin.include_tasks: data-retention.yml
- ansible.builtin.include_tasks: secure-secure-shell.yml
- ansible.builtin.include_tasks: unattended-upgrades.yml
- ansible.builtin.include_tasks: user-convenience.yml
- ansible.builtin.include_tasks: post-tasks.yml
