---
- name: fail for deprecated variable
  ansible.builtin.fail:
    msg: Variable basics_autoupdate_blacklist has been renamed to basics_autoupdate_blocklist
  when: basics_autoupdate_blacklist is defined

- name: use ansible_lsb distribution
  ansible.builtin.set_fact:
    distribution: "{{ ansible_lsb.id }}"
  when: ansible_lsb.id is defined

- name: use ansible_facts distribution
  ansible.builtin.set_fact:
    distribution: "{{ ansible_facts['distribution'] }}"
  when: ansible_lsb.id is not defined

- name: show distribution
  ansible.builtin.debug: var=distribution

- name: include OS-dependent variables
  ansible.builtin.include_vars:
    file: os_{{ distribution }}.yml

- name: install requirements for some Ansible operations
  ansible.builtin.apt:
    name:
      - curl
      - git
      - gpg
      - unzip
    cache_valid_time: 86400
