---
- name: use ansible_lsb distribution
  ansible.builtin.set_fact:
    distribution: "{{ ansible_lsb.id }}"
  when: ansible_lsb.id is defined

- name: use ansible_facts distribution
  ansible.builtin.set_fact:
    distribution: "{{ ansible_facts['distribution'] }}"
  when: ansible_lsb.id is not defined

- name: show distribution
  ansible.builtin.debug: var=distribution

- name: include OS-dependent variables
  ansible.builtin.include_vars:
    file: os_{{ distribution }}.yml

- name: configure hostname
  ansible.builtin.hostname:
    name: "{{ basics_hostname }}"
  when: basics_hostname is defined

- name: install requirements for some Ansible operations
  ansible.builtin.apt:
    name:
      - curl
      - git
      - gpg
      - unzip
    cache_valid_time: 86400
