# Secure SSH Configuration
# https://stribika.github.io/2015/01/04/secure-secure-shell.html
---
- name: check for ED25519 host key
  ansible.builtin.stat: path=/etc/ssh/ssh_host_ed25519_key
  register: f
- ansible.builtin.fail: msg="No ED25519 host key found"
  when: not f.stat.exists

- name: check for RSA host key
  ansible.builtin.stat: path=/etc/ssh/ssh_host_rsa_key
  register: f
- ansible.builtin.fail: msg="No RSA host key found"
  when: not f.stat.exists

- name: template sshd_config
  ansible.builtin.template:
    src: sshd_config
    dest: /etc/ssh/
    backup: yes
  register: sshd_config

- name: reload sshd immediately
  ansible.builtin.service:
    name: ssh
    state: reloaded
  when: sshd_config.changed
