---
- name: install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades

- name: install update-notifier-common
  ansible.builtin.apt:
    name: update-notifier-common
  when: ansible_distribution == "Ubuntu"

- name: copy 10periodic
  ansible.builtin.copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/

- name: template 50unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/

- name: ensure apt-daily.timer override directory
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory

- name: template apt-daily.timer override
  ansible.builtin.template:
    src: timer-override.conf
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
  vars:
    on_calendar: "{{ basics_autoupdate_update_calendar }}"
    randomized_delay: "{{ basics_autoupdate_update_delay }}"
  notify: reload systemd

- name: ensure apt-daily-upgrade.timer override directory
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory

- name: template apt-daily-upgrade.timer override
  ansible.builtin.template:
    src: timer-override.conf
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
  vars:
    on_calendar: "{{ basics_autoupdate_upgrade_calendar }}"
    randomized_delay: "{{ basics_autoupdate_upgrade_delay }}"
  notify: reload systemd
