---
- name: remove vim-tiny
  ansible.builtin.apt:
    name: vim-tiny
    state: absent
    purge: yes

- name: install user-friendly packages
  ansible.builtin.apt:
    name:
      - htop
      - less
      - screen
      - tree
      - vim
      - wget

- name: check for /etc/screenrc
  ansible.builtin.stat: path=/etc/screenrc
  register: f

- name: disable screen startup message
  ansible.builtin.lineinfile:
    dest: /etc/screenrc
    regexp: '^#(startup_message off)$'
    line: '\1'
    backrefs: yes
    backup: yes
  when: f.stat.exists
