---
- name: install packages
  ansible.builtin.apt:
    name: "{{ nginx_packages }}"
    cache_valid_time: 86400

- name: template nginx.conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/
    backup: yes
  notify: reload nginx

- name: template bad_user_agents
  ansible.builtin.template:
    src: bad_user_agents
    dest: /etc/nginx/
  when: nginx_bad_user_agents
  notify: reload nginx

- name: remove bad_user_agents
  ansible.builtin.file:
    path: /etc/nginx/bad_user_agents
    state: absent
  when: not nginx_bad_user_agents
  notify: reload nginx

- name: copy nginx files
  ansible.builtin.copy:
    src: nginx/
    dest: /etc/nginx/
  notify: reload nginx

- name: add application/wasm to mime.types
  ansible.builtin.lineinfile:
    path: /etc/nginx/mime.types
    line: "    application/wasm                      wasm;"
    insertbefore: "application/x.*"
    firstmatch: yes
    backup: yes
  notify: reload nginx

- name: template default site
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-available/
  notify: reload nginx

- name: enable default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    src: /etc/nginx/sites-available/default
    state: link
  when: nginx_default_site
  notify: reload nginx

- name: disable default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: not nginx_default_site
  notify: reload nginx

- name: copy nginx-site script
  ansible.builtin.copy:
    src: nginx-site
    dest: /usr/local/sbin/
    mode: 0750
    owner: root
    group: www-data

- name: template openssl.cnf
  ansible.builtin.template:
    src: openssl.cnf
    dest: /etc/ssl/
    backup: yes
  notify: restart nginx

- name: generate default certificate
  ansible.builtin.command: /usr/bin/openssl req -x509 -subj "/CN=default" -days 3650 -sha256 -out /etc/ssl/default.crt -newkey rsa:2048 -nodes -keyout /etc/ssl/default.key
  args:
    creates: /etc/ssl/default.crt

- name: create ACME webroot
  ansible.builtin.file:
    path: "{{ acme_webroot }}"
    state: directory
    mode: 0750
    owner: root
    group: www-data
  register: webroot

- name: copy restart.conf
  ansible.builtin.copy:
    src: systemd/restart.conf
    dest: /etc/systemd/system/nginx.service.d/
  when: nginx_systemd_restart
  notify: reload systemd

- name: remove restart.conf
  ansible.builtin.file:
    path: /etc/systemd/system/nginx.service.d/restart.conf
    state: absent
  when: not nginx_systemd_restart
  notify: reload systemd

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  when: webroot.changed
