---
- name: remove folder
  ansible.builtin.file:
    path: "{{ golang_path }}"
    state: absent

- name: create folder
  ansible.builtin.file:
    path: "{{ golang_path }}"
    state: directory

- name: download release
  ansible.builtin.get_url:
    url: "{{ golang_url }}"
    dest: /tmp/golang.tar.gz
    checksum: "{{ golang_checksum }}"
    mode: 0444

- name: unarchive release
  ansible.builtin.unarchive:
    src: /tmp/golang.tar.gz
    dest: "{{ golang_path }}"
    extra_opts: "--strip-components=1"
    remote_src: yes

- name: remove archive
  ansible.builtin.file:
    path: /tmp/golang.tar.gz
    state: absent
