namespace: alxndr42
name: commons
version: 2.1.0
readme: README.md
authors: ["Alexander Dietrich"]
description: Basic infrastructure for Debian-based servers.
license: GPL-3.0-or-later
tags:
  - certbot
  - debian
  - golang
  - nginx
  - ubuntu
repository: https://codeberg.org/alxndr42/ansible-commons
build_ignore:
  - .gitignore
  - tmp
