#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: ensure-python <python_version>"
    echo ""
    echo "Installs the given Python version for the current user using pyenv,"
    echo "if necessary, and prints the absolute path to the Python executable."
    echo ""
    echo "The Python version can be a prefix."
    exit 1
fi

# https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

if ! PYTHON_VERSION=$(pyenv latest -k "$1"); then
    exit 1
fi

if ! pyenv install -s "$PYTHON_VERSION" > /dev/null 2>&1; then
    echo "Python $PYTHON_VERSION installation failed."
    exit 1
fi

if ! pyenv shell "$PYTHON_VERSION" > /dev/null 2>&1; then
    echo "Python $PYTHON_VERSION activation failed."
    exit 1
fi

pyenv which python
