# https://wiki.debian.org/DebianRepository/UseThirdParty
# https://github.com/nodesource/distributions

---
- name: remove old signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: absent

- name: create signing key directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '755'

- name: download signing key
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.key
    checksum: sha256:332d428848005f43bfc79b9578c55cd172f5f17ae38aa7d9328f03a24e21c13a
    # Fingerprint: 6F71 F525 2828 41EE DAF8  51B4 2F59 B5F9 9B1B E0B4

- name: remove old repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/{{ nodejs_version }} {{ ansible_lsb.codename }} main"
    filename: nodesource
    state: absent

- name: add repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.key] https://deb.nodesource.com/{{ nodejs_version }} nodistro main"
    filename: nodesource

- name: install packages
  apt:
    name: "{{ nodejs_packages }}"
    cache_valid_time: 86400
