---
- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
