---
- name: install packages
  apt:
    name: "{{ certbot_packages }}"
    cache_valid_time: 86400

- name: template cli.ini
  template:
    src: cli.ini
    dest: /etc/letsencrypt/

- name: create ACME webroot
  file:
    path: "{{ acme_webroot }}"
    state: directory
    mode: 0750
    owner: root
    group: www-data

- name: populate service facts
  service_facts:

- name: copy nginx renewal hook
  copy:
    src: nginx
    dest: /etc/letsencrypt/renewal-hooks/post/
    mode: 0755
  when: "'nginx' in services"

- name: remove nginx renewal hook
  file:
    path: /etc/letsencrypt/renewal-hooks/post/nginx
    state: absent
  when: "'nginx' not in services"
